#!/usr/bin/with-contenv ash

chown nginx:nginx /var/www/api -R

mkdir /var/log/frog
touch /var/log/frog/access.log
chmod 777 /var/log/frog/ -R

echo 0 > /tmp/nginx
echo 0 > /tmp/php-fpm
echo 0 > /tmp/logs


